### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by temecom** [lifegadget/ui-selectize#26]
In a new project, after installing using:  

ember install ui-selectize

On 'ember serve' the app throws: 

ENOENT, no such file or directory '/home/csmith/Development/dali/dali-analytics-ui/tmp/concat_with_maps-input_base_path-3BzJUx7f.tmp/0/bower_components/selectize/dist/js/standalone/selectize.js'
Error: ENOENT, no such file or directory '/home/csmith/Development/dali/dali-analytics-ui/tmp/concat_with_maps-input_base_path-3BzJUx7f.tmp/0/bower_components/selectize/dist/js/standalone/selectize.js'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at ConcatWithMaps.keyForFile (/home/csmith/Development/dali/dali-analytics-ui/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/home/csmith/Development/dali/dali-analytics-ui/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:112:65)
    at /home/csmith/Development/dali/dali-analytics-ui/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/home/csmith/Development/dali/dali-analytics-ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/csmith/Development/dali/dali-analytics-ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/home/csmith/Development/dali/dali-analytics-ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/home/csmith/Development/dali/dali-analytics-ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

Removing the ui-selectize package clears the error but obviously I cannot use the control. 

Versions: 

 npm --version
2.11.3
 ember --version
version: 1.13.8
node: 0.12.7
npm: 2.13.4
os: linux x64
 bower --version
1.7.2

**Comment by yankeeinlondon** [comment]
It appears the bower dependency didn't install, should be able to use this right away by `bower install --save selectize`. Obviously it was "supposed" to do that when you installed ui-selectize. I'll keep this issue open and see if I can find out why but this shouldn't prevent you from using it.
